"""
The Bouncer - Stage 2 Filter
Blocks vendor/library files and generated code from being scanned.
This prevents false positives from third-party dependencies.
"""

import os
import json
from pathlib import Path
from typing import Set, List


class FileBouncer:
    """
    Filters out vendor, library, and generated files before security scanning.
    """
    
    def __init__(self, knowledge_base_path: str = "backend/knowledge/safe_patterns.json"):
        """
        Initialize the bouncer with safe patterns from knowledge base.
        
        Args:
            knowledge_base_path: Path to the JSON file containing safe patterns
        """
        self.safe_dirs: Set[str] = set()
        self.safe_extensions: Set[str] = set()
        self.safe_file_patterns: Set[str] = set()
        
        # Load knowledge base
        self._load_knowledge_base(knowledge_base_path)
        
        # Additional heuristic patterns
        self.vendor_keywords = {
            'vendor', 'third_party', 'external', 'dependencies',
            'bower_components', 'jspm_packages', 'packages'
        }
        
        self.generated_keywords = {
            'generated', 'auto-generated', 'autogenerated',
            'compiled', 'bundled', 'minified'
        }
    
    def _load_knowledge_base(self, kb_path: str) -> None:
        """Load safe patterns from the knowledge base JSON file."""
        try:
            if os.path.exists(kb_path):
                with open(kb_path, 'r', encoding='utf-8') as f:
                    kb = json.load(f)
                    
                # Load safe directories
                self.safe_dirs = set(kb.get('safe_directories', []))
                
                # Load safe file patterns
                patterns = kb.get('safe_file_patterns', [])
                for pattern in patterns:
                    if pattern.startswith('*.'):
                        # Extract extension
                        self.safe_extensions.add(pattern[1:])  # Remove *
                    else:
                        self.safe_file_patterns.add(pattern)
                        
        except Exception as e:
            print(f"Warning: Could not load knowledge base from {kb_path}: {e}")
            # Use defaults
            self._set_defaults()
    
    def _set_defaults(self) -> None:
        """Set default safe patterns if knowledge base is unavailable."""
        self.safe_dirs = {
            'node_modules', 'venv', '.venv', 'build', 'dist',
            'vendor', 'lib', 'libs', 'contracts/lib', '__pycache__',
            '.git', 'migrations', 'alembic'
        }
        self.safe_extensions = {
            '.min.js', '.min.css', '.map', '.lock', '.pyc',
            '.pyo', '.so', '.dll', '.dylib', '.wasm'
        }
        self.safe_file_patterns = {
            'package-lock.json', 'yarn.lock', 'poetry.lock',
            'Pipfile.lock', 'composer.lock'
        }
    
    def is_vendor_or_generated(self, file_path: str) -> bool:
        """
        Determine if a file should be blocked from scanning.
        
        Args:
            file_path: Path to the file (relative or absolute)
            
        Returns:
            True if file should be blocked (is vendor/generated), False otherwise
        """
        # Normalize path
        normalized_path = Path(file_path).as_posix()
        path_parts = normalized_path.split('/')
        filename = os.path.basename(normalized_path)
        
        # Check 1: Is it in a safe directory?
        if self._is_in_safe_directory(path_parts):
            return True
        
        # Check 2: Does it have a safe extension?
        if self._has_safe_extension(filename):
            return True
        
        # Check 3: Is it a known safe file pattern?
        if filename in self.safe_file_patterns:
            return True
        
        # Check 4: Heuristic - contains vendor keywords in path?
        if self._contains_vendor_keywords(normalized_path.lower()):
            return True
        
        # Check 5: Heuristic - file appears to be generated?
        if self._appears_generated(filename, normalized_path):
            return True
        
        # Check 6: Is it a binary or compiled file?
        if self._is_binary_or_compiled(filename):
            return True
        
        return False
    
    def _is_in_safe_directory(self, path_parts: List[str]) -> bool:
        """Check if any part of the path matches safe directories."""
        for part in path_parts:
            if part in self.safe_dirs:
                return True
            # Check for partial matches with safe dirs
            for safe_dir in self.safe_dirs:
                if safe_dir in part:
                    return True
        return False
    
    def _has_safe_extension(self, filename: str) -> bool:
        """Check if file has a safe extension."""
        for ext in self.safe_extensions:
            if filename.endswith(ext):
                return True
        return False
    
    def _contains_vendor_keywords(self, path_lower: str) -> bool:
        """Check if path contains vendor-related keywords."""
        return any(keyword in path_lower for keyword in self.vendor_keywords)
    
    def _appears_generated(self, filename: str, full_path: str) -> bool:
        """
        Heuristic check if file appears to be auto-generated.
        
        Indicators:
        - Filename contains 'generated', 'compiled', etc.
        - Minified files (.min.js, .min.css)
        - Source maps (.map)
        - Very long filenames with hashes (webpack bundles)
        """
        filename_lower = filename.lower()
        path_lower = full_path.lower()
        
        # Check for generation keywords
        if any(keyword in filename_lower or keyword in path_lower 
               for keyword in self.generated_keywords):
            return True
        
        # Check for webpack-style hashed filenames
        # e.g., main.a1b2c3d4.js
        if '.' in filename:
            parts = filename.split('.')
            if len(parts) >= 3:  # name.hash.ext
                # Check if middle part looks like a hash (8+ alphanumeric chars)
                middle = parts[-2]
                if len(middle) >= 8 and middle.isalnum():
                    return True
        
        return False
    
    def _is_binary_or_compiled(self, filename: str) -> bool:
        """Check if file is a binary or compiled artifact."""
        binary_extensions = {
            '.exe', '.dll', '.so', '.dylib', '.bin', '.dat',
            '.pyc', '.pyo', '.class', '.jar', '.war', '.ear',
            '.wasm', '.o', '.a', '.lib', '.obj'
        }
        return any(filename.endswith(ext) for ext in binary_extensions)
    
    def filter_files(self, file_paths: List[str]) -> tuple[List[str], List[str]]:
        """
        Filter a list of files into allowed and blocked lists.
        
        Args:
            file_paths: List of file paths to filter
            
        Returns:
            Tuple of (allowed_files, blocked_files)
        """
        allowed = []
        blocked = []
        
        for file_path in file_paths:
            if self.is_vendor_or_generated(file_path):
                blocked.append(file_path)
            else:
                allowed.append(file_path)
        
        return allowed, blocked
    
    def get_filter_stats(self, file_paths: List[str]) -> dict:
        """
        Get statistics about filtering results.
        
        Args:
            file_paths: List of file paths to analyze
            
        Returns:
            Dictionary with filtering statistics
        """
        allowed, blocked = self.filter_files(file_paths)
        
        return {
            'total_files': len(file_paths),
            'allowed_files': len(allowed),
            'blocked_files': len(blocked),
            'block_rate': f"{(len(blocked) / len(file_paths) * 100):.1f}%" if file_paths else "0%",
            'blocked_list': blocked[:10]  # Show first 10 blocked files
        }


# Convenience function for backward compatibility
def is_vendor_or_generated(file_path: str) -> bool:
    """
    Standalone function to check if a file should be blocked.
    
    Args:
        file_path: Path to the file
        
    Returns:
        True if file should be blocked, False otherwise
    """
    bouncer = FileBouncer()
    return bouncer.is_vendor_or_generated(file_path)


if __name__ == "__main__":
    # Test the bouncer
    bouncer = FileBouncer()
    
    test_files = [
        "node_modules/web3/index.js",
        "src/main.js",
        "build/bundle.min.js",
        "venv/lib/python3.9/site-packages/requests/__init__.py",
        "backend/main.py",
        "frontend/src/components/Dashboard.js",
        "repo/src/js/web3.min.js",
        "package-lock.json",
        "contracts/lib/SafeMath.sol",
        "src/utils/helpers.js"
    ]
    
    print("Testing File Bouncer\n" + "="*50)
    for file in test_files:
        blocked = bouncer.is_vendor_or_generated(file)
        status = "🚫 BLOCKED" if blocked else "✅ ALLOWED"
        print(f"{status}: {file}")
    
    print("\n" + "="*50)
    stats = bouncer.get_filter_stats(test_files)
    print(f"\nFilter Statistics:")
    print(f"Total Files: {stats['total_files']}")
    print(f"Allowed: {stats['allowed_files']}")
    print(f"Blocked: {stats['blocked_files']}")
    print(f"Block Rate: {stats['block_rate']}")
